# sever listen port
port: 8080
# tmdb api key
api_key: ""
# http proxy address
proxy: "http://127.0.0.1:7890"
# path of unrecognized files
raw_path: C:\Desktop
# path of tv files
tv_path: ""
# path of movie files
movie_path : ""
# scan interval
delay : 60