version: "3"
services:
  anime-repository-web:
    image: yoaken/anime-repository-web
    container_name: anime-repository-web
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/anime-repository-web/config.yml:rw
      - ./data/:/app/anime-repository-web/data/:rw
      - ./Downloads/:/app/anime-repository-web/downloads/:rw
      - ./collections/:/app/anime-repository-web/collections/:rw
      # add paths as the volumes to dispose video files
    environment:
      - GIN_MODE=release
    network_mode: "host"

