version: "3"
services:
  anime-repository-web:
    image: yoaken/anime-repository-web
    container_name: anime-repository-web
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml ./config.yml
    environment:
      - GIN_MODE=release