# name: Build Released
# on:
#   push:
#     # branches:
#     #   - master
#     tags:
#       - 'v*'
#     permissions:
#       contents: write 
#   jobs:
#     setup_environment:
#       steps:
#         # Setup and configure GoLang
#         - name: Setup GoLang
#           uses: actions/setup-go@v4
#           with:
#             go-version: ${{inputs.go-version}}
#         # Setup and configure NodeJS
#         - name: Setup NodeJS
#           uses: actions/setup-node@v3
#           with:
#             node-version: ${{inputs.node-version}}
#         - name: install pnpm
#           shell: bash
#           run: npm i pnpm@latest -g
#         # Building step
#         - name: Build App
#           if: inputs.build == 'true' &&  runner.os == 'Linux'
#           working-directory: ${{ inputs.app-working-directory }}
#           run: go build -o ${{inputs.build-name}} && cd ./frontend && pnpm build  
#           shell: bash
#         - name: Build App
#           if: inputs.build == 'true' && runner.os == 'Windows'
#           working-directory: ${{ inputs.app-working-directory }}
#           run: go build -o ${{inputs.build-name}} 
#           shell: bash
#         - name: Add Linux perms
#           if: inputs.build == 'true' && runner.os  == 'Linux'
#           working-directory: ${{ inputs.app-working-directory }}
#           run: chmod +x build/bin/*
#           shell: bash